language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pep8

# command to run tests
script: 
  - find . -name \*.py -exec pep8 --ignore=E402 {} +
  - python tests.py
